export const STUDY_DOMAIN = {
    INFORMATIQUE: "INFORMATIQUE",
    PSYCHOLOGIE: "PSYCHOLOGIE",
    ARCHITECTURE: "ARCHITECTURE",
    ELECTROTECHNIQUE: "ELECTROTECHNIQUE",
    HISTOIRE: "HISTOIRE",
    MUSIQUE: "MUSIQUE",
    SCIENCES: "SCIENCES",
    ARTS: "ARTS",
    GEOGRAPHIE: "GEOGRAPHIE",
    CINEMA: "CINEMA"
};